In [2]:
pip install pandas numpy scikit-learn



[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd
df=pd.read_csv("train.csv")


/var/folders/6c/z629mdg533g0vw1w531yx00m0000gn/T/ipykernel_16503/3025702528.py:2: DtypeWarning: Columns (0: Monthly_Balance) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("train.csv")


In [4]:
df = pd.read_csv("train.csv", low_memory=False)

In [5]:
df.shape

(100000, 28)

In [6]:
df.columns.tolist()

['ID',
 'Customer_ID',
 'Month',
 'Name',
 'Age',
 'SSN',
 'Occupation',
 'Annual_Income',
 'Monthly_Inhand_Salary',
 'Num_Bank_Accounts',
 'Num_Credit_Card',
 'Interest_Rate',
 'Num_of_Loan',
 'Type_of_Loan',
 'Delay_from_due_date',
 'Num_of_Delayed_Payment',
 'Changed_Credit_Limit',
 'Num_Credit_Inquiries',
 'Credit_Mix',
 'Outstanding_Debt',
 'Credit_Utilization_Ratio',
 'Credit_History_Age',
 'Payment_of_Min_Amount',
 'Total_EMI_per_month',
 'Amount_invested_monthly',
 'Payment_Behaviour',
 'Monthly_Balance',
 'Credit_Score']

In [7]:
df["Credit_Score"].value_counts()

Credit_Score
Standard    53174
Poor        28998
Good        17828
Name: count, dtype: int64

In [8]:
df.isnull().sum().sort_values(ascending=False).head(15)

Monthly_Inhand_Salary       15002
Type_of_Loan                11408
Name                         9985
Credit_History_Age           9030
Num_of_Delayed_Payment       7002
Amount_invested_monthly      4479
Num_Credit_Inquiries         1965
Monthly_Balance              1200
ID                              0
Changed_Credit_Limit            0
Payment_Behaviour               0
Total_EMI_per_month             0
Payment_of_Min_Amount           0
Credit_Utilization_Ratio        0
Outstanding_Debt                0
dtype: int64

In [9]:
df["Age"].head(20)

0       23
1       23
2     -500
3       23
4       23
5       23
6       23
7       23
8      28_
9       28
10      28
11      28
12      28
13      28
14      28
15      28
16      34
17      34
18      34
19      34
Name: Age, dtype: str

In [10]:
df["Annual_Income"].head(20)

0      19114.12
1      19114.12
2      19114.12
3      19114.12
4      19114.12
5      19114.12
6      19114.12
7      19114.12
8      34847.84
9      34847.84
10    34847.84_
11     34847.84
12     34847.84
13     34847.84
14     34847.84
15     34847.84
16    143162.64
17    143162.64
18    143162.64
19    143162.64
Name: Annual_Income, dtype: str

In [11]:
df["Outstanding_Debt"].head(20)

0      809.98
1      809.98
2      809.98
3      809.98
4      809.98
5      809.98
6      809.98
7      809.98
8      605.03
9      605.03
10     605.03
11     605.03
12     605.03
13     605.03
14     605.03
15     605.03
16    1303.01
17    1303.01
18    1303.01
19    1303.01
Name: Outstanding_Debt, dtype: str

In [12]:
df["Num_of_Loan"].head(20)

0     4
1     4
2     4
3     4
4     4
5     4
6     4
7     4
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    3
17    3
18    3
19    3
Name: Num_of_Loan, dtype: str

In [13]:
y=df["Credit_Score"]
X=df.drop(columns=["Credit_Score","ID","Customer_ID","Name","SSN"])

In [14]:
numerical_cols = [
    "Age",
    "Annual_Income",
    "Num_of_Loan",
    "Num_of_Delayed_Payment",
    "Outstanding_Debt",
    "Changed_Credit_Limit",
    "Amount_invested_monthly",
    "Monthly_Balance"
]


In [15]:
for col in numerical_cols:
    X[col] = pd.to_numeric(
        X[col].astype(str).str.replace("_",""),
        errors="coerce")

In [16]:
X[numerical_cols].info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column                   Non-Null Count   Dtype  
---  ------                   --------------   -----  
 0   Age                      100000 non-null  int64  
 1   Annual_Income            100000 non-null  float64
 2   Num_of_Loan              100000 non-null  int64  
 3   Num_of_Delayed_Payment   92998 non-null   float64
 4   Outstanding_Debt         100000 non-null  float64
 5   Changed_Credit_Limit     97909 non-null   float64
 6   Amount_invested_monthly  95521 non-null   float64
 7   Monthly_Balance          98800 non-null   float64
dtypes: float64(6), int64(2)
memory usage: 6.1 MB


In [17]:
X.isnull().sum().sort_values(
    ascending=False
).head(15)

Monthly_Inhand_Salary      15002
Type_of_Loan               11408
Credit_History_Age          9030
Num_of_Delayed_Payment      7002
Amount_invested_monthly     4479
Changed_Credit_Limit        2091
Num_Credit_Inquiries        1965
Monthly_Balance             1200
Num_of_Loan                    0
Interest_Rate                  0
Delay_from_due_date            0
Age                            0
Num_Credit_Card                0
Num_Bank_Accounts              0
Credit_Mix                     0
dtype: int64

In [18]:
numerical_features = X.select_dtypes(include=["int64", "float64"]).columns

for col in numerical_features:
    X[col] = X[col].fillna(X[col].median())

In [19]:
categorical_features = X.select_dtypes(include=["object"]).columns

for col in categorical_features:
    X[col] = X[col].fillna(X[col].mode()[0])

/var/folders/6c/z629mdg533g0vw1w531yx00m0000gn/T/ipykernel_16503/801182930.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_features = X.select_dtypes(include=["object"]).columns


In [20]:
X.isnull().sum().sum()

np.int64(0)

In [21]:
X.select_dtypes(include="object").columns.tolist()

/var/folders/6c/z629mdg533g0vw1w531yx00m0000gn/T/ipykernel_16503/1679899076.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  X.select_dtypes(include="object").columns.tolist()


['Month',
 'Occupation',
 'Type_of_Loan',
 'Credit_Mix',
 'Credit_History_Age',
 'Payment_of_Min_Amount',
 'Payment_Behaviour']

In [22]:
for col in X.select_dtypes(include=["object"]).columns:
    print(f"\n{col}")
    print(X[col].unique()[:10])


Month
<ArrowStringArray>
['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August']
Length: 8, dtype: str

Occupation
<ArrowStringArray>
[    'Scientist',       '_______',       'Teacher',      'Engineer',
  'Entrepreneur',     'Developer',        'Lawyer', 'Media_Manager',
        'Doctor',    'Journalist']
Length: 10, dtype: str

Type_of_Loan
<ArrowStringArray>
['Auto Loan, Credit-Builder Loan, Personal Loan, and Home Equity Loan',
                                                 'Credit-Builder Loan',
                             'Auto Loan, Auto Loan, and Not Specified',
                                                       'Not Specified',
                              'Credit-Builder Loan, and Mortgage Loan',
                          'Not Specified, Auto Loan, and Student Loan',
               'Personal Loan, Debt Consolidation Loan, and Auto Loan',
                                      'Not Specified, and Payday Loan',
                   'Credit-Builder Loan, 

/var/folders/6c/z629mdg533g0vw1w531yx00m0000gn/T/ipykernel_16503/543508160.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in X.select_dtypes(include=["object"]).columns:


In [23]:
def convert_history_age(text):
    years = int(text.split(" Years")[0])
    months = int(text.split(" and ")[1].split(" Months")[0])

    return years * 12 + months

In [24]:
X["Credit_History_Age_Months"] = X["Credit_History_Age"].apply(
    convert_history_age
)

In [25]:
X = X.drop("Credit_History_Age", axis=1)

In [26]:
X = X.drop("Type_of_Loan", axis=1)

In [27]:
from sklearn.preprocessing import LabelEncoder

le_occ = LabelEncoder()

X["Occupation"] = le_occ.fit_transform(
    X["Occupation"]
)

In [28]:
le_month = LabelEncoder()

X["Month"] = le_month.fit_transform(
    X["Month"]
)

In [29]:
le_mix = LabelEncoder()

X["Credit_Mix"] = le_mix.fit_transform(
    X["Credit_Mix"]
)

In [30]:
le_pay = LabelEncoder()

X["Payment_of_Min_Amount"] = le_pay.fit_transform(
    X["Payment_of_Min_Amount"]
)

In [31]:
le_beh = LabelEncoder()

X["Payment_Behaviour"] = le_beh.fit_transform(
    X["Payment_Behaviour"]
)

In [32]:
from sklearn.preprocessing import LabelEncoder

target_encoder = LabelEncoder()

y = target_encoder.fit_transform(y)

In [33]:
X["Debt_to_Income"] = (
    X["Outstanding_Debt"] /
    (X["Annual_Income"] + 1)
)

In [34]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 23 columns):
 #   Column                     Non-Null Count   Dtype  
---  ------                     --------------   -----  
 0   Month                      100000 non-null  int64  
 1   Age                        100000 non-null  int64  
 2   Occupation                 100000 non-null  int64  
 3   Annual_Income              100000 non-null  float64
 4   Monthly_Inhand_Salary      100000 non-null  float64
 5   Num_Bank_Accounts          100000 non-null  int64  
 6   Num_Credit_Card            100000 non-null  int64  
 7   Interest_Rate              100000 non-null  int64  
 8   Num_of_Loan                100000 non-null  int64  
 9   Delay_from_due_date        100000 non-null  int64  
 10  Num_of_Delayed_Payment     100000 non-null  float64
 11  Changed_Credit_Limit       100000 non-null  float64
 12  Num_Credit_Inquiries       100000 non-null  float64
 13  Credit_Mix                 100000 non-nul

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [36]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(80000, 23)
(20000, 23)
(80000,)
(20000,)


In [37]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=101,
    random_state=31
)

rf.fit(X_train, y_train)


,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",101
,"random_state random_state: int, RandomState instance or None, default=NoneControls both the randomness of the bootstrapping of the samples usedwhen building trees (if ``bootstrap=True``) and the sampling of thefeatures to consider when looking for the best split at each node(if ``max_features < n_features``).See :term:`Glossary <random_state>` for details.",31
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstr

In [38]:
y_pred = rf.predict(X_test)

In [39]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test, y_pred)

print("Accuracy:", acc)

Accuracy: 0.79


In [40]:
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_predi))

NameError: name 'y_predi' is not defined

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=101,
    random_state=42
)

scores = cross_val_score(
    rf,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print(scores)
print("Mean Accuracy:", scores.mean())

In [ ]:
print(df["Customer_ID"].nunique())
print(len(df))

In [ ]:
print(rf)

In [ ]:
import numpy as np

unique, counts = np.unique(y, return_counts=True)

for u, c in zip(unique, counts):
    print(f"Class {u}: {c}")


In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

rf_test = RandomForestClassifier(
    n_estimators=101,
    random_state=42
)

scores = cross_val_score(
    rf_test,
    X_train,
    y_train,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

print(scores)
print("Mean:", scores.mean())

In [ ]:
import joblib

joblib.dump(rf, "creditiq_model.pkl")

In [ ]:
joblib.dump(le_month, "month_encoder.pkl")
joblib.dump(le_occ, "occupation_encoder.pkl")
joblib.dump(le_mix, "credit_mix_encoder.pkl")
joblib.dump(le_pay, "payment_encoder.pkl")
joblib.dump(le_beh, "behaviour_encoder.pkl")
joblib.dump(target_encoder, "target_encoder.pkl")

In [41]:
print(rf)

RandomForestClassifier(n_estimators=101, random_state=31)


In [42]:
rf.predict(X_test[:5])

array([1, 1, 1, 2, 2])

In [49]:
import joblib
loaded_model = joblib.load("creditiq_model.pkl")

loaded_model.predict(X_test[:5])

array([1, 1, 1, 2, 2])

In [45]:
import joblib

print("RF test:")
print(rf.predict(X_test[:5]))

joblib.dump(rf, "creditiq_model.pkl")

loaded_model = joblib.load("creditiq_model.pkl")

print("\nLoaded model test:")
print(loaded_model.predict(X_test[:5]))

RF test:
[1 1 1 2 2]

Loaded model test:
[1 1 1 2 2]


In [46]:
import os

print(os.getcwd())

/Users/aarushisingh/ml_codealpha/credit_score


In [47]:
import os

print(os.path.abspath("creditiq_model.pkl"))

/Users/aarushisingh/ml_codealpha/credit_score/creditiq_model.pkl
